@startuml
left to right direction

skinparam backgroundColor #FFFFFF
skinparam defaultFontName Arial
skinparam defaultFontSize 13
skinparam roundcorner 20
skinparam shadowing true

title Архитектура сервиса анализа безопасности API\nс AI интеграцией на всех этапах анализа

rectangle "UI, CI/CD или\nдругие клиенты" as Client #87CEEB
rectangle "Запрос с выбором банка\nVBank / ABank / SBank\n" as Bank #FFD700
rectangle "Получение\nOpenAPI спецификации\nпо URL" as OpenAPI #98FB98

rectangle "Статический\nанализ\nOWASP Top 10" as Static #FFA500
rectangle "Динамический\nанализ\nHTTP запросы\nBOLA тесты" as Dynamic #FF7F50
rectangle "Валидация\nконтракта\nСравнение ответов" as Contract #FF6347
rectangle "ИИ анализ\nдополнение рекомендаций\nпо устранению уязвимостей" as AIANALYSIS #FF6347

rectangle "AI Интеграция\nФильтрация FP\nГенерация рекомендаций\nКонтекстный анализ" as AI #DA70D6
rectangle "Яндекс.Cloud\nAI Agent\n(для хакатона - QWEN 3-235B)" as Yandex #90EE90

rectangle "Генерация и \nпредоставление\nотчетов\nPDF / JSON / HTML" as Reports #FFD700
rectangle "Хранилище\nIn-Memory\nПерсистентность\nв будущем" as Storage #D3D3D3

Client --> Bank
Bank --> OpenAPI
OpenAPI --> Static
AI <-> Yandex

Static <-> AI

Static --> Dynamic
Dynamic <-> AI

Dynamic --> Contract
Contract <-> AI

Contract --> AIANALYSIS
AIANALYSIS <-> AI

AIANALYSIS --> Reports
Reports <-> Storage
Client <-> Reports

@enduml

